import {MigrationInterface, QueryRunner} from "typeorm";

export class FakePosts1628887502049 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
        insert into post (title, text, "creatorId", "createdAt") values ('Hands of the Ripper', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1, '2021-06-04T09:42:01Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Queens Logic', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2020-09-26T02:26:12Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Dragon Ball: The Path to Power (Doragon bôru: Saikyô e no michi)', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2021-06-09T00:49:55Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Maria (Mariya)', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, '2021-06-18T13:18:10Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Kocken', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, '2020-08-20T12:33:52Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Wallace & Gromit in The Curse of the Were-Rabbit', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2021-07-31T11:34:37Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Shade', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1, '2021-06-01T12:51:23Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Ladies They Talk About', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2020-12-26T00:11:37Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Broken', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2020-10-22T10:15:14Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Immigrants (L.A. Dolce Vita)', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1, '2021-05-25T14:40:51Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Liberty Heights', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, '2021-03-22T08:56:50Z');
        insert into post (title, text, "creatorId", "createdAt") values ('March or Die', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2021-06-18T11:15:43Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Loose Change 9/11: An American Coup', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2021-07-12T01:30:06Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Mothra (Mosura)', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2021-05-25T04:43:38Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Untamed Heart', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2021-06-10T21:35:16Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Ten Thousand Saints', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, '2021-03-18T15:21:49Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Blue Hawaii', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2020-10-22T17:53:12Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Analyze This', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2021-08-06T17:34:38Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Fourth State, The (Die vierte Macht)', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, '2021-06-12T00:15:16Z');
        insert into post (title, text, "creatorId", "createdAt") values ('William Vincent (Shadows and Lies)', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2020-08-20T10:56:38Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Private Function, A', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, '2021-01-21T11:07:35Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Warriors, The', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, '2020-10-22T05:25:37Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Paraíso Travel', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1, '2021-01-14T08:52:10Z');
        insert into post (title, text, "creatorId", "createdAt") values ('13 Assassins (Jûsan-nin no shikaku)', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, '2021-05-03T07:12:59Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Charge of the Light Brigade, The', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, '2020-10-13T22:30:19Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Night Has a Thousand Eyes', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2021-07-20T12:11:37Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Sergeant Rutledge', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, '2021-03-30T17:42:08Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Cabin Fever: Patient Zero', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, '2021-07-17T13:29:23Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Confess', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2021-07-03T10:09:20Z');
        insert into post (title, text, "creatorId", "createdAt") values ('La liga no es cosa de hombres', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2021-02-06T19:10:54Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Couch Trip, The', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2021-02-24T19:22:14Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Airplane II: The Sequel', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, '2020-09-01T16:21:26Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Monsoon Wedding', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, '2020-10-30T20:42:05Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Purgatory', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, '2021-01-18T01:14:16Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Babes in Arms', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2020-12-28T11:12:54Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Player, The', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2020-12-28T01:39:13Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Save the Green Planet! (Jigureul jikyeora!)', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1, '2020-09-19T01:12:57Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Bitch, The (La chienne)', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2020-09-27T16:21:14Z');
        insert into post (title, text, "creatorId", "createdAt") values ('SOS - en segelsällskapsresa', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1, '2021-04-30T03:39:15Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Suspiria', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2020-12-27T21:08:29Z');
        insert into post (title, text, "creatorId", "createdAt") values ('To Sir with Love', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1, '2020-12-29T08:17:41Z');
        insert into post (title, text, "creatorId", "createdAt") values ('MC5*: A True Testimonial', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1, '2021-07-12T02:26:38Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Gay Divorcee, The', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2020-08-21T02:46:54Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Dakota Skye', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2020-12-18T04:14:20Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Butcher Boys (Bone Boys)', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1, '2021-03-27T12:10:05Z');
        insert into post (title, text, "creatorId", "createdAt") values ('300', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2020-11-25T17:33:53Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Holes', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, '2020-10-04T06:21:44Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Go for It', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, '2020-11-15T18:34:36Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Life Stinks', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, '2020-12-23T19:37:28Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Vegas Vacation (National Lampoon''s Las Vegas Vacation)', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2021-02-12T23:26:45Z');
    `)
    }

    public async down(_: QueryRunner): Promise<void> {
    }

}
